version: '3'
services:
  api:
    image: sample-express-app
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  web-cli:
    image: sample-express-app
    command: sh
