swagger: "2.0"
info:
  description: "This is a simple sample server. It can store and retrieve JSON documents from a DynamoDB."
  version: "1.0.0"
  title: "Simple API Template"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/v2"
tags:
- name: "documents"
  description: "Store and retrieve JSON documents"
schemes:
- "https"
- "http"
paths:
  /documents:
    post:
      tags:
      - "documents"
      summary: "Add a new document to the data store"
      description: ""
      operationId: "addDocument"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "A new document that needs to be added to the data store"
        required: true
        schema:
          $ref: "#/definitions/Document"
      responses:
        405:
          description: "Invalid input"
    get:
      tags:
      - "documents"
      summary: "Get all documents"
      description: "Returns all documents"
      operationId: "getDocuments"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Document"
        404:
          description: "Document not found"
  /documents/{documentId}:
    get:
      tags:
      - "documents"
      summary: "Find a document by ID"
      description: "Returns a single document"
      operationId: "getDocumentById"
      produces:
      - "application/json"
      parameters:
      - name: "documentId"
        in: "path"
        description: "ID of document to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Document"
        404:
          description: "Document not found"
definitions:
  Document:
    type: "object"
    properties:
      id:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"